id: P002921
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21827
  title: འབྲས་རྩིས་བར་གསལ་ལི་དྭངས་མའི་མེ་ལོང་།
  author: ''
  volumes:
    a4e27fcdf7a64a45bace28b64e148fc6:
      image_group_id: I1KG21916
      title: ''
      volume_number: 1
      total_pages: 292
      base_file: v001.txt
